### ISSUE TITLE
Datapack doesn't show up in datapack list

### ISSUE THREAD

**Issue by SatoshiKitagawa** [misode/no-trial-chambers#1]
When I create a world and try to add this datapack in the pack folder it doesnt show up in the select datapack page. Even when I create a world without the datapack and add it later in the game files it doesn't show up when I run /datapack list. Am I doing something wrong?

I'm using Vanilla 1.20.4 and v1.2

Edit: I don't know if this was clear from my previous message, but the datapack doesn't work for me.

Edit 2: Should I add the experimental features 1.21 datapack at world creation and then disable them or should I not add them at all? (Tried both btw and it didn't work)

**Comment by Riannanas** [comment]
I have this too

**Comment by misode** [comment]
@SatoshiKitagawa The data pack is supposed to be added when you create the world, not after. Are you using any mods together with this?

**Comment by misode** [comment]
@jimmyfrost Where did you download this from if the file is named `no-trial-chambers-main.zip`? You should get it either from [Modrinth](https://modrinth.com/datapack/no-trial-chambers) or from [GitHub releases](https://github.com/misode/no-trial-chambers/releases/latest).

**Comment by Lardbutt200** [comment]
I also have the same issue. fabric 1.20.4 v1.2. I tried creating the world with the pack, i tried adding the pack after creating the world, i even tried the mod. all to no avail. the mod shows up in the mod list but no new blocks are in the creative menu. with the datapack, it didnt show up in /datapack list

**Comment by misode** [comment]
@Lardbutt200 Okay I believe the issue here is an outdated version of Fabric API.

Update to the latest beta version `0.95.4`: https://modrinth.com/mod/fabric-api/version/0.95.4+1.20.4

**Comment by jimmyfrost** [comment]
> @jimmyfrost Where did you download this from if the file is named `no-trial-chambers-main.zip`? You should get it either from [Modrinth](https://modrinth.com/datapack/no-trial-chambers) or from [GitHub releases](https://github.com/misode/no-trial-chambers/releases/latest). Also I didn't test this on either Apex or Paper, so there may be issues with those.

I tried to apply this to an existing world. I take it that is my issue. I downloaded the zip here from github btw.

**Comment by sakura-ryoko** [comment]
FYI, using the mod and the fabric API version worked for me after having the above problems.

**Comment by misode** [comment]
@Nefride Adding it to an existing world does not world. You need to add it from the start. There are some workarounws mentioned in #2 if you're interested.

**Comment by SatoshiKitagawa** [comment]
> @SatoshiKitagawa The data pack is supposed to be added when you create the world, not after. Are you using any mods together with this?

No, I'm not

**Comment by misode** [comment]
@SatoshiKitagawa I am not sure what could be causing the issue for you. Could you provide some more info:
* Can you show a screenshot of the output from `/datapack list`
* How exactly did you create your world? Did you enable any experiments or other data packs?
* Can you auto-complete `/locate structure trial_cha`? Can you find the crafter in the creative inventory? Can you `/give @s crafter`?

**Comment by SatoshiKitagawa** [comment]
When I download the mod or the datapack (_update_1_21_no_trial_chambers_1.20.4.zip_) from modrinth everything works fine.
When I download the datapack from GitHub (_no-trial-chambers-main.zip_ or _no-trial-chambers-1.2_) it doesn't work.
Here are some screenshots: (Everything looks the same for both versions)
![Screenshot (17)](https://github.com/misode/no-trial-chambers/assets/159055777/7f7a8893-970d-47a6-b11c-84031589bbb8)
![Screenshot (18)](https://github.com/misode/no-trial-chambers/assets/159055777/c5132f01-c980-45f6-b48d-86fee0ed98b6)
![Screenshot (19)](https://github.com/misode/no-trial-chambers/assets/159055777/6ddd2cae-5f5b-4be0-9d58-848ff8f734b6)
![Screenshot (20)](https://github.com/misode/no-trial-chambers/assets/159055777/2fc86ef8-7459-44fe-9642-0145b4be3c77)
![Screenshot (23)](https://github.com/misode/no-trial-chambers/assets/159055777/0b444849-0f30-48f9-833b-2b2c287194ac)

**Comment by misode** [comment]
Thank you for the help! I figured out what the problem was. I forgot to attach the data pack zip when I made the release on GitHub, so you downloaded the source, which contains an extra folder inside the zip.

@Riannanas @jimmyfrost The issue should be fixed now.
