### ISSUE TITLE
Installing on an existing world

### ISSUE THREAD

**Issue by PDBaqueiro** [misode/no-trial-chambers#10]
I tried adding this to my pre-existing world, but when adding it to the datapack folder, it is not listed on the datapack list nor the new recipes are added. I could add them to a new world without issues by selecting the datapack on the list of datapacks to add, but no success adding it to my existing world. Can you please assist me with it?

**Comment by xshanaj** [comment]
go to modrinth and download the the fabric version and install into your mods folder, i had the same problem and after looking into the closed tickets i tried the fabric version on modrinth and it worked perfectly!!!

**Comment by misode** [comment]
@PDBaqueiro I have updated the description with instructions for adding to an existing world

**Comment by PDBaqueiro** [comment]
> @PDBaqueiro I have updated the description with instructions for adding to an existing world

THANK YOU SO MUCH! You are the best!
