### ISSUE TITLE
Not installed correctly

### ISSUE THREAD

**Issue by Ldog274** [misode/no-trial-chambers#12]
First I would like to make sure that this data pack is compatible with sprigot servers. second, I have pasted the no_trial_chambers_main.zip file into the data packs folder of my world data and enabled the features in the level.dat file, but the blocks are not craftable and the datapack is not listed when I use /datapacks list. I am not sure what I have done wrong. was there a different ziped file that I was supposed to download?

**Comment by misode** [comment]
You have the wrong zip file. You need to download it either from here: https://github.com/misode/no-trial-chambers/releases/tag/v1.2 or here https://modrinth.com/datapack/no-trial-chambers

**Comment by Ldog274** [comment]
ahhhhhhh thank you so much! I just followed the link from Xisuma's Redit post about the hermitcraft 10 world info to get here lol.

**Comment by misode** [comment]
Thanks for letting me know about this post 👍
