### ISSUE TITLE
Can't seem to let pack work

### ISSUE THREAD

**Issue by GewoonNiek** [misode/no-trial-chambers#19]
I followed the full tutorial, added the things in de level.dat file but it still doesnt say that the pack is there.
If i want to do /datapack enable (pack) it says "Pack 'update_1_21' cannot be enabled, since required flags are not enabled in this world: minecraft:update_1_21!"

Does anyone know a fix for this?

**Comment by misode** [comment]
@GewoonNiek Do NOT run `/datapack enable` on the separate update_1_21 (feature) entry. Only enable the no trial chambers one. Make sure that you edit and save the level.dat while the world/server is fully closed and then reopen the world.

If those tips do not fix your issues, could you let me know whether you're using any mods/plugins/other data packs?

**Comment by GewoonNiek** [comment]
It's fixed, thanks for the help! I think the issue was me not fully stopping the server while updating the level.dat file
