### ISSUE TITLE
Missing Metadata

### ISSUE THREAD

**Issue by cpro2000** [misode/no-trial-chambers#3]
Forgive me as I am naive in github and modding, because in my attempts to add the data pack to a already existing server I receive the error "Missing metadata in pack file/no-trial-chamber-main"

As for functionality, the datapack appears in game with all recipes and items however all items are disabled despite " /datapack enabled "said datapack" and /datapack list " stating the datapack is enabled.

**Comment by cpro2000** [comment]
As well as, the no-trial-chamber-main file does have the pack.mcmeta text file

**Comment by misode** [comment]
@cpro2000 From where did you download the data pack?

> As for functionality, the datapack appears in game with all recipes and items however all items are disabled despite " /datapack enabled "said datapack" and /datapack list " stating the datapack is enabled.

Did you make sure NOT to add the data pack to an existing world? Only adding to a new world is supported. If you're interested in a workaround, see #2.

**Comment by cpro2000** [comment]
Ah, it is an existing world. I misunderstood the fix and it is working now. Thank you very much for your patience
