### ISSUE TITLE
will the datapack update to the new witch loot drop mechanic or more updates in general?

### ISSUE THREAD

**Issue by W33ST** [misode/no-trial-chambers#30]
as the tittle says. don't have really more to say. 
if i wrote this on the tap. let me know and sorry in advanced.

**Comment by misode** [comment]
I am not planning to release a version of this data pack for 1.21. This was made to allow servers like Hermitcraft to play with the new blocks (which felt pretty stable) without including the (experimental) trial chambers.

**Comment by W33ST** [comment]
sorry if i wasn't clear. i meant  with release of the new snapshot, witches loot table has changed so that it will always drop Redstone dust. will there be a version of this datapack including that change for version 1.20.+ ?

**Comment by misode** [comment]
The redstone drop change was made in a snapshot for 1.21. As I said I will not make a release for 1.21. If you want to play in 1.20.4 with increased redstone drops, it shouldn't be too hard for yourself to add this loot table.
