### ISSUE TITLE
what can i do if i want to add this datapack into my 1.20.1 world

### ISSUE THREAD

**Issue by Lullabird** [misode/no-trial-chambers#31]
my world is in 1.20.1 version, forge. and i have a mod witch haven't update to any higher version yet. plz tell me what can i do

**Comment by misode** [comment]
That is not possible. The data pack relies on the experimental flag, which wasn't available in 1.20.1. If you want to use the 1.21 blocks in 1.20.1, you'll have to look for an actual mod that backports the blocks.
