### ISSUE TITLE
How do i add this datapack on server creation

### ISSUE THREAD

**Issue by Cooilleeneyder** [misode/no-trial-chambers#4]
Maybe it´s a dumb question but I´m new to the servr business.
How do i create a linux server with this datapack. If states that if i add it to an exiting world it doesn´t work, but I have to create the world to add it... I´m confused :(

**Comment by misode** [comment]
You can put the zip file inside the `world/datapacks` folder, and then run the server jar for the first time.

**Comment by Cooilleeneyder** [comment]
Thx a lot, for creating his datapack and helping dummies like me :D
