### ISSUE TITLE
How to install in a new world?

### ISSUE THREAD

**Issue by Ravn73** [misode/no-trial-chambers#5]
If i have to put this in the datapack of a new world? The world (save) doesnt exist, so there is no way that i can do that?

**Comment by misode** [comment]
When creating a world in single player you can use the More > Data Packs screen and drop the data pack there. For multiplayer you can create the folders `world/datapacks` manually and put the zip in there, before running the server jar for the first time.

**Comment by Dingy1731** [comment]
Not really a 'new world' issue, just curious how to add it to my existing world even though its in my data packs and I've reloaded the world and restarted the game/launcher

**Comment by misode** [comment]
@Dingy1731 See #2 for instructions on how to enable it on an existing world
