### ISSUE TITLE
crafter is a disabled item

### ISSUE THREAD

**Issue by briannelson95** [misode/no-trial-chambers#6]
I'm installing this in an existing world, I've read through all the other open issues and tried to troubleshoot with the tips listed. 

- tried installing just the `update_1_21_no_trial_chambers_1.20.4.zip` datapack 
- tried installing just the `no-trial-chambers-1.2.jar` mod
- tried installing both the datapack and the mod
- edit `level.dat` using nbtstudio to include `update_1_21` in the enabled datapacks
- tried installing the older version of just the datapack
- tried installing the older version of just the mod
- tried installing both the older versions of the datapack and the mod

What I've figured out is having both the datapack and the mod installed shows that I've unlocked the recipes but when I go to craft the crafter I'm hit with `Disabled item` and am unable to get any output from the crafting table. How do I `enable` the item?

**Comment by briannelson95** [comment]
Update: issue still presists however, if I try to run the command in game `/datapack enable update_1_21` I receive this error message:
```
Pack 'update_1_21' cannot be enabled, since required flags are not enabled in this world: minecraft:update_1_21!
```

Seems like I need to figure out whatever the required flags are to enable the items

**Comment by briannelson95** [comment]
**To add to existing fabric world**
- add `no-trial-chambers-1.2.jar` to mods folder
- add `update_1_21_no_trial_chambers_1.20.4.zip` to world\datapacks folder
- edit `world\level.dat` to include a list on the `Data` entry called `enabled_features`
- add 2 string items to this list: 
  - `minecraft:vanilla` and `minecraft:update_1_21`
- restart server

**Comment by misode** [comment]
You don't need to add both the mod and the data pack, one of them should work. And yeah when adding to an existing world you need to modify the level.dat

**Comment by drewrubinstein** [comment]
My level.dat is just random characters how do I include Data on enabled_features

**Comment by misode** [comment]
@drewrubinstein Use an NBT editing tool such as [NBT Studio](https://github.com/tryashtar/nbt-studio/releases) or [NBT Viewer](https://marketplace.visualstudio.com/items?itemName=Misodee.vscode-nbt)

**Comment by drewrubinstein** [comment]
I did but every time i save as an experimental world, I open the world and it resets

**Comment by briannelson95** [comment]
Make sure to save the file before reopening the world. I would suggest making sure that both the world and minecraft game is closed while editing the level.dat file

**Comment by misode** [comment]
I have updated the description with instructions for adding to an existing world
