### ISSUE TITLE
Installing into a server

### ISSUE THREAD

**Issue by KingArthurGames** [misode/no-trial-chambers#8]
I'm trying to add this to a fresh aternos server and they have it in the list of mods but none of the ways I've downloaded it have allowed me to put it in curseforge to run with the rest of the server's mods nor can I find it by searching curseforge. It's likely I'm just being a dummy as this is my first custom modded server but my buddies and I would love to play with the auto crafter! What am I missing?

**Comment by misode** [comment]
The mod is not published on curseforge. You can find it on Modrinth: https://modrinth.com/datapack/no-trial-chambers

**Comment by Sk1Lpha** [comment]
I've tried using the mod for my server and it's the only one I cant seem to get to work. Is there anything that needs to be enabled or anything after installing? Do I also need to follow the same thing as the datapack when adding to an existing world?
